AWSTemplateFormatVersion: '2010-09-09'
Description: >
  digital-ingest-pipeline

  Pipeline for ingesting packages of born-digital and digitized content.

Mappings:
  DeployResources:
    CloudFormationBucket:
      dev: rac-dev-cloudformation-apps
      prod: rac-prod-cloudformation-apps
    CloudFormationBucketPrefix:
      dev: digital_ingest_pipeline
      prod: digital_ingest_pipeline
    SecurityGroup:
      dev: "sg-0f98d77d7bb7b4ce6"
      prod: "sg-0a568e8a6ff39b710" 
    Subnet:
      dev: "subnet-098df07b0ab91cb1d"
      prod: "subnet-02e68cd17b1abfc14"
  NotificationsLambda:
    ZodiacBaseurl:
      dev: "https://zodiac.dev.rockarch.org/api"
      prod: "https://zodiac.rockarch.org/api"
  TriggerLambda:
    ECSSubnetName:
      dev: "subnet-098df07b0ab91cb1d"
      prod: "subnet-0102189437e2babd8"
  DiscoveryService:
    SourceBucketName:
      dev: "rac-dev-digital-ingest-upload"
      prod: "rac-prod-digital-ingest-upload"
    DigitizationEfsId:
      dev: "fs-4ecb5eae"
      prod: "fs-b9197b5a"
    DigitizationEfsAccessPointId: 
      dev: "fsap-0d530b00165a90a27"
      prod: "" # TODO
    DigitizationRootPath:
      dev: "pictor"
      prod: "pictor"
    DigitizationPath:
      dev: "src"
      prod: "src"
    DigitizationUrl:
      dev: "https://zodiac.dev.rockarch.org:8012"
      prod: "https://zodiac.rockarch.org:8012"  

Parameters:
  Environment:
    Type: String
    Description: The environment in which the infrastructure should be deployed.
    AllowedValues:
      - dev
      - prod
    Default: dev

Resources:
  # Temporary Storage
  TemporaryStorage:
    Type: AWS::EFS::FileSystem
    Properties: 
      Encrypted: true
      FileSystemTags: 
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: digital-ingest-temporary-storage
      LifecyclePolicies: 
        - TransitionToIA: AFTER_30_DAYS
      PerformanceMode: generalPurpose
      ThroughputMode: elastic

  # Temporary Storage Access Point
  TemporaryStorageAccessPoint:
    Type: 'AWS::EFS::AccessPoint'
    Properties:
      AccessPointTags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: digital-ingest-temporary-storage
      FileSystemId: !Ref TemporaryStorage
      PosixUser:
        Uid: "1000"
        Gid: "1000"
      RootDirectory:
        CreationInfo:
          OwnerGid: "1000"
          OwnerUid: "1000"
          Permissions: "755"
        Path: "/digital-ingest"
  
  # ECS Cluster
  DigitalIngestECSCluster:
    Type: AWS::ECS::Cluster
    Properties: 
      CapacityProviders: 
        - FARGATE
      ClusterName: DigitalIngestCluster
      Tags: 
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: digital-ingest-ecs-cluster

  # Discovery ECS Task
  DiscoveryTask:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        !Join ["/", 
          [
          "https://s3.amazonaws.com",
          !FindInMap [DeployResources, CloudFormationBucket, !Ref Environment],
          !FindInMap [DeployResources, CloudFormationBucketPrefix, !Ref Environment],
          "digital_ingest_discovery_template.yaml"
          ]
        ]
      Parameters:
        ApplicationEnvironment: !Ref Environment
        ApplicationName: digital_ingest_discovery
        EfsId: !Ref TemporaryStorage
        EfsAccessPointId: !Ref TemporaryStorageAccessPoint
        EfsRootPath: '/efs'
        EventsTopicArn: !Ref DigitalIngestTopic
        StoragePath: 'storage'
        TemporaryPath: 'digital_ingest_discovery_tmp'
        SourceBucketName: !FindInMap [DiscoveryService, SourceBucketName, !Ref Environment]
        DigitizationEfsId: !FindInMap [DiscoveryService, DigitizationEfsId, !Ref Environment]
        DigitizationEfsAccessPointId: !FindInMap [DiscoveryService, DigitizationEfsAccessPointId, !Ref Environment]
        DigitizationRootPath: !FindInMap [DiscoveryService, DigitizationRootPath, !Ref Environment]
        DigitizationPath: !FindInMap [DiscoveryService, DigitizationPath, !Ref Environment]
        DigitizationUrl: !FindInMap [DiscoveryService, DigitizationUrl, !Ref Environment]

  # Assembly ECS Task
  AssemblyTask:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        !Join ["/", 
          [
          "https://s3.amazonaws.com",
          !FindInMap [DeployResources, CloudFormationBucket, !Ref Environment],
          !FindInMap [DeployResources, CloudFormationBucketPrefix, !Ref Environment],
          "digital_ingest_assembly_template.yaml"
          ]
        ]
      Parameters:
        ApplicationEnvironment: !Ref Environment
        ApplicationName: digital_ingest_assembly
        EfsId: !Ref TemporaryStorage
        EfsAccessPointId: !Ref TemporaryStorageAccessPoint
        EfsRootPath: '/efs'
        # What else?

  # Transformation ECS Task
  TransformationTask:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        !Join ["/", 
          [
          "https://s3.amazonaws.com",
          !FindInMap [DeployResources, CloudFormationBucket, !Ref Environment],
          !FindInMap [DeployResources, CloudFormationBucketPrefix, !Ref Environment],
          "digital_ingest_transformation_template.yaml"
          ]
        ]
      Parameters:
        ApplicationEnvironment: !Ref Environment
        ApplicationName: digital_ingest_transformation
        EfsId: !Ref TemporaryStorage
        EfsAccessPointId: !Ref TemporaryStorageAccessPoint
        EfsRootPath: '/efs'
        # What else?

  # SNS topic
  DigitalIngestTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: digital-ingest-notifications    
  
  # SQS Notifications Queue
  DigitalIngestNotificationsQueue:
    Type: AWS::SQS::Queue
    Properties:
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: digital-ingest-notifications-queue

  # SQS Trigger Queue
  DigitalIngestTriggerQueue:
    Type: AWS::SQS::Queue
    Properties:
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: digital-ingest-notifications-queue

  # SNS Subscription for SQS Notifications Queue
  DigitalIngestNotificationsQueueSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !GetAtt DigitalIngestTopic.Arn
      Protocol: sqs
      Endpoint: !GetAtt DigitalIngestNotificationsQueue.Arn
      FilterPolicy: '"requested_status": [{"exists": false}]'
      FilterPolicyScope: MessageAttributes

  # SNS Subscription for SQS Trigger Queue
  DigitalIngestTriggerQueueSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !GetAtt DigitalIngestTopic.Arn
      Protocol: sqs
      Endpoint: !GetAtt DigitalIngestTriggerQueue.Arn
      FilterPolicy: '"requested_status": [{"exists": true}]'
      FilterPolicyScope: MessageAttributes
  
  # Notifications Lambda
  NotificationsLambda:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        !Join ["/", 
          [
          "https://s3.amazonaws.com",
          !FindInMap [DeployResources, CloudFormationBucket, !Ref Environment],
          !FindInMap [DeployResources, CloudFormationBucketPrefix, !Ref Environment],
          "digital_ingest_notifications_template.yaml"
          ]
        ]
      Parameters:
        ApplicationEnvironment: !Ref Environment
        ApplicationName: digital_ingest_notifications
        EventsTopicArn: !Ref DigitalIngestTopic
        NotificationsQueueArn: !Ref DigitalIngestNotificationsQueue
        ZodiacBaseurl: !FindInMap [NotificationsLambda, ZodiacBaseurl, !Ref Environment]

  # Trigger Lambda
  TriggerLambda:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        !Join ["/", 
          [
          "https://s3.amazonaws.com",
          !FindInMap [DeployResources, CloudFormationBucket, !Ref Environment],
          !FindInMap [DeployResources, CloudFormationBucketPrefix, !Ref Environment],
          "digital_ingest_trigger_template.yaml"
          ]
        ]
      Parameters:
        ApplicationEnvironment: !Ref Environment
        ApplicationName: digital_ingest_trigger
        ECSClusterName: !Ref DigitalIngestECSCluster
        ECSSubnetName: !FindInMap [TriggerLambda, ECSSubnetName, !Ref Environment]
        ParentStackName: !Ref AWS::StackName
        SourceBucketName: !FindInMap [DiscoveryService, SourceBucketName, !Ref Environment]
        TriggerQueueArn: !Ref DigitalIngestTriggerQueue

  # Webhook Lambda
  WebhookLambda:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        !Join ["/", 
          [
          "https://s3.amazonaws.com",
          !FindInMap [DeployResources, CloudFormationBucket, !Ref Environment],
          !FindInMap [DeployResources, CloudFormationBucketPrefix, !Ref Environment],
          "digital_ingest_webhook_template.yaml"
          ]
        ]
      Parameters:
        ApplicationEnvironment: !Ref Environment
        ApplicationName: digital_ingest_webhook
        ParentStackName: !Ref AWS::StackName
        NotificationsTopicArn: !Ref DigitalIngestTopic