AWSTemplateFormatVersion: '2010-09-09'
Description: >
  digital-ingest-transformation

  Transforms data from Aurora and makes Accessions,
  Archival Objects, and Digital Objects in ArchivesSpace.

Parameters:
# The AWS account that hosts the Amazon Elastic Container Registry (ECR) repository
  ContainerAccountId:
    Type: String
    Description: Account ID under which container repository is located.
    Default: "817658541382"
  ApplicationEnvironment:
    Type: String
    Description: Environment in which application should be deployed.
    AllowedValues:
      - dev
      - prod
    # Do we need a default defined like in digital_ingest_pipeline_template.yml?
  ApplicationName:
    Type: String
    Description: Name of the application to be deployed.
  ARCHIVEMATICA_SS_API_KEY:
    Type: String
    Description: API Key for Archivematica Storage Service
  ARCHIVEMATICA_SS_USER_NAME:
    Type: String
    Description: Archivematica Storage Service Username
  ARCHIVEMATICA_SS_URL: 
    Type: String
    Description: URL for the Archivematica Storage Service
  ZODIAC_BASEURL:
    Type: String
    Description: BaseURL for the Zodiac Backend
  AS_BASEURL:
    Type: String
    Description: BaseURL for the ArchivesSpace Backend
  AS_USERNAME:
    Type: String
    Description: ArchivesSpace Username
  AS_PASSWORD:
    Type: String
    Description: ArchivesSpace Password
  AS_REPO_ID:
    Type: Number
    Description: ArchivesSpace Repository ID
  AURORA_BASEURL:
    Type: String
    Description: Aurora BaseURL
  AURORA_OAUTH_CLIENT_BASEURL:
    Type: String
    Description: Aurora OAuth Client BaseURL
  AURORA_OAUTH_CLIENT_ID:
    Type: String
    Description: Aurora OAuth Client ID
  AURORA_OAUTH_CLIENT_SECRET:
    Type: String
    Description: Aurora OAuth Client Secret
  AURORA_ACCESSION_STARTED_STATUS:
    Type: String
    Description: Status of Aurora Accession at start
  AURORA_PACKAGE_COMPLETE_STATUS:
    Type: String
    Description: Status of Aurora Accession at completion
  IIIF_MANIFEST_BASEURL:
    Type: String
    Description: BaseURL for the IIIF manifest
  DOWNLOAD_BASEURL:
    Type: String
    Description: BaseURL to download the object
  # Elastic File System (EFS) parameters for temporary storage of files as they are transformed and moved through the pipeline
  EfsId:
    Type: String
    Description: Identifier for temporary storage EFS.
  EfsAccessPointId:
    Type: String
    Description: Identifier for temporary storage EFS access point.
  EfsRootPath:
    Type: String
    Description: Root path at which EFS is mounted.
  StoragePath:
    Type: String
    Description: Location in EFS mount at which source files are stored.
  TemporaryPath:
    Type: String
    Description: Location in EFS mount at which files are unpacked.

  # S3 bucket where transformed files are stored
  # Not sure this is necessary. It's not being used anywhere AFAIK
  SourceBucketName:
    Type: String
    Description: Name of S3 bucket to which packaged files should be delivered.

  # Elastic File System (EFS) parameters for digitization delivery for packages that are not from Aurora
  DigitizationEfsId:
    Type: String
    Description: Identifier for digitization delivery EFS.
  DigitizationEfsAccessPointId:
    Type: String
    Description: Identifier for digitization delivery EFS access point.
  DigitizationRootPath:
    Type: String
    Description: Root path for digitized delivery.
  DigitizationPath:
    Type: String
    Description: Path to deliver packages of digitized content for further processing.
  DigitizationUrl:
    Type: String
    Description: URL to post to to trigger further processing for packages of digitized content.

  EventsTopicArn:
    Type: String
    Description: ARN for events SNS Topic

Resources:
  # I think we need this, but could be wrong.
  SnsTopicParam:
    Type: AWS::SSM::Parameter
    Properties: 
      AllowedPattern: "^[A-Za-z0-9\\-\\_]+$"
      Description: ARN for SNS topic to send messages to.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/SNS_TOPIC
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
      Type: String
      Value: !Ref EventsTopicArn

  # An ECS task definition that defines the container
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: LogPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource:
                  - !GetAtt TransformationLogGroup.Arn
        - PolicyName: EcrPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:BatchGetImage'
                Resource:
                  - !Sub arn:aws:ecr:${AWS::Region}:${ContainerAccountId}:repository/${ApplicationName}
              - Effect: Allow
                Action:
                  - 'ecr:GetAuthorizationToken'
                Resource: '*'

  TransformationUser:
    Type: AWS::IAM::User
    UserName: TransformationUser

  TransformationUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref TransformationUser

  TransformationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !GetAtt TransformationUser.Arn
            Action:
              - 'sts:AssumeRole'
      Description: 'Allows access to SSM parameters.'
      Policies:
        - PolicyName: TransformationSNSPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 'sns:Publish'
                Resource:
                  - !Ref EventsTopicArn
        - PolicyName: TransformationSSMPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ssm:GetParametersByPath'
                Resource:
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ApplicationEnvironment}/${ApplicationName}

  TransformationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/rac/${ApplicationEnvironment}/digital_ingest/ecs/${ApplicationName}"
      RetentionInDays: 90

  TransformationEcsTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: "1024"
      Memory: "3072"
      SNS_ROLE_ARN: !GetAtt TransformationRole.Arn
      SSM_ROLE_ARN: !GetAtt TransformationRole.Arn
      SNS_TOPIC: !Ref EventsTopicArn
      # Currently don't know where this comes from/what it is
      PACKAGE_ID: !Ref PackageID
      ContainerDefinitions:
        - Name: !Ref ApplicationName
          Image: !Sub "${ContainerAccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ApplicationName}:latest"
          Essential: true
          Environment:
            Variables:
              Env: !Ref ApplicationEnvironment
              ARCHIVEMATICA_SS_API_KEY: !Ref ARCHIVEMATICA_SS_API_KEY
              ARCHIVEMATICA_SS_USER_NAME: !Ref ARCHIVEMATICA_SS_USER_NAME
              ARCHIVEMATICA_SS_URL: !Ref ARCHIVEMATICA_SS_URL
              ZODIAC_BASEURL: !Ref ZODIAC_BASEURL
              AS_BASEURL: !Ref AS_BASEURL
              AS_USERNAME: !Ref AS_USERNAME
              AS_PASSWORD: !Ref AS_PASSWORD
              AS_REPO_ID: !Ref AS_REPO_ID
              AURORA_BASEURL: !Ref AURORA_BASEURL
              AURORA_OAUTH_CLIENT_BASEURL: !Ref AURORA_OAUTH_CLIENT_BASEURL
              AURORA_OAUTH_CLIENT_ID: !Ref AURORA_OAUTH_CLIENT_ID
              AURORA_OAUTH_CLIENT_SECRET: !Ref AURORA_OAUTH_CLIENT_SECRET
              AURORA_ACCESSION_STARTED_STATUS: !Ref AURORA_ACCESSION_STARTED_STATUS
              AURORA_PACKAGE_COMPLETE_STATUS: !Ref AURORA_PACKAGE_COMPLETE_STATUS
              IIIF_MANIFEST_BASEURL: !Ref IIIF_MANIFEST_BASEURL
              DOWNLOAD_BASEURL: !Ref DOWNLOAD_BASEURL
              APP_CONFIG_PATH: !Ref ApplicationName
              AWS_REGION: !Ref AWS::Region
          Tags:
            - Key: Environment
              Value: !Ref ApplicationEnvironment
            - Key: Application
              Value: !Ref ApplicationName

          MountPoints:
            - SourceVolume: efs
              ContainerPath: !Ref EfsRootPath
              ReadOnly: false
            - SourceVolume: digitization
              ContainerPath: !Ref DigitizationRootPath
              ReadOnly: false
          LogConfiguration:
            LogDriver: awslogs
            Options:
              "awslogs-group": !Ref TransformationLogGroup
              "awslogs-region": !Ref AWS::Region
              "awslogs-stream-prefix": "ecs"
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      Family: !Ref ApplicationName
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      RuntimePlatform:
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX
      Volumes:
        - Name: efs
          EFSVolumeConfiguration:
            FilesystemId: !Ref EfsId
            RootDirectory: /
            TransitEncryption: ENABLED
            AuthorizationConfig:
              AccessPointId: !Ref EfsAccessPointId
              IAM: DISABLED
        - Name: digitization
          EFSVolumeConfiguration:
            FilesystemID: !Ref DigitizationEfsId
            RootDirectory: /
            TransitEncryption: ENABLED
            AuthorizationConfig:
              AccessPointId: !Ref DigitizationEfsAccessPointId
              IAM: DISABLED

Outputs:
  TransformationArn:
    Description: Transformation ECS Task Definition ARN
    Value: !Ref TransformationEcsTask