AWSTemplateFormatVersion: 2010-09-09
Description: >
  digital-ingest-transformation

  Transforms data from Aurora and makes Accessions,
  Archival Objects, and Digital Objects in ArchivesSpace.

Parameters:
  ContainerAccountId:
    Type: String
    Description: Account ID under which container repository is located.
    Default: "817658541382"
  ApplicationEnvironment:
    Type: String
    Description: Environment in which application should be deployed.
    AllowedValues:
      - dev
      - prod
    Default: dev
  ApplicationName:
    Type: String
    Description: Name of the application to be deployed.
  EventsTopicArn:
    Type: String
    Description: ARN for events SNS Topic.
  ArchivematicaSsApiKey:
    Type: String
    Description: API Key for Archivematica Storage Service.
  ArchivematicaSsUserName:
    Type: String
    Description: User for Archivematica Storage Service.
  ArchivematicaSsUrl:
    Type: String
    Description: Base URL for Archivematica Storage Service.
  ZodiacBaseurl:
    Type: String
    Description: Base URL for Zodiac.
  ArchivesSpaceBaseurl:
    Type: String
    Description: Base URL for ArchivesSpace.
  ArchivesSpaceUsername:
    Type: String
    Description: Username for ArchivesSpace.
  ArchivesSpacePassword:
    Type: String
    Description: Password for ArchivesSpace.
  ArchivesSpaceRepoId:
    Type: String
    Description: Repo ID for ArchivesSpace.
  AuroraBaseurl:
    Type: String
    Description: Base URL for Aurora.
  AuroraOauthClientBaseurl:
    Type: String
    Description: OAuth client base URL for Aurora.
  AuroraOauthClientId:
    Type: String
    Description: OAuth Client ID for Aurora
  AuroraOauthClientSecret:
    Type: String
    Description: OAuth Client Secret for Aurora.
  AuroraAccessionStartedStatus:
    Type: String
    Description: Process status for accession started in Aurora.
  AuroraPackageCompleteStatus:
    Type: String
    Description: Process status for package complete in Aurora.
  IiifManifestBaseurl:
    Type: String
    Description: Base URL for IIIF Manifests.
  DownloadBaseurl:
    Type: String
    Description: Base URL for downloadable assets.

Resources:
  ArchivematicaSsApiKeyParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: API Key for Archivematica Storage Service.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/ARCHIVEMATICA_SS_API_KEY
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
      Type: String
      Value: !Ref ArchivematicaSsApiKey
  ArchivematicaSsUserNameParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: User for Archivematica Storage Service.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/ARCHIVEMATICA_SS_USER_NAME
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
      Type: String
      Value: !Ref ArchivematicaSsUserName
  ArchivematicaSsUrlParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: Base URL for Archivematica Storage Service.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/ARCHIVEMATICA_SS_URL
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
      Type: String
      Value: !Ref ArchivematicaSsUrl
  ZodiacBaseurlParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: ARN for role with permissions for lambda.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/ZODIAC_BASEURL
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
      Type: String
      Value: !Ref ZodiacBaseurl
  ArchivesSpaceBaseurlParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: Base URL for ArchivesSpace.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/AS_BASEURL
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
      Type: String
      Value: !Ref ArchivesSpaceBaseurl
  ArchivesSpaceUsernameParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: Username for ArchivesSpace.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/AS_USERNAME
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
      Type: String
      Value: !Ref ArchivesSpaceUsername
  ArchivesSpacePasswordParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: Password for ArchivesSpace.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/AS_PASSWORD
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
      Type: String
      Value: !Ref ArchivesSpacePassword
  ArchivesSpaceRepoIdParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: Repository ID for ArchivesSpace.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/AS_REPO_ID
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
      Type: String
      Value: !Ref ArchivesSpaceRepoId
  AuroraBaseurlParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: Base URL for Aurora.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/AURORA_BASEURL
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
      Type: String
      Value: !Ref AuroraBaseurl
  AuroraOauthClientBaseurlParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: Base URL for Aurora OAuth client.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/AURORA_OAUTH_CLIENT_BASEURL
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
      Type: String
      Value: !Ref AuroraOauthClientBaseurl
  AuroraOauthClientIdParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: Client ID for Aurora OAuth client.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/AURORA_OAUTH_CLIENT_ID
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
      Type: String
      Value: !Ref AuroraOauthClientId
  AuroraOauthClientSecretParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: Client Secret for Aurora OAuth client.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/AURORA_OAUTH_CLIENT_SECRET
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
      Type: String
      Value: !Ref AuroraOauthClientSecret
  AuroraAccessionStartedStatusParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: Process status for accessioning started in Aurora.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/AURORA_ACCESSION_STARTED_STATUS
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
      Type: String
      Value: !Ref AuroraAccessionStartedStatus
  AuroraPackageCompleteStatusParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: Process status for package complete in Aurora.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/AURORA_PACKAGE_COMPLETE_STATUS
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
      Type: String
      Value: !Ref AuroraPackageCompleteStatus
  IiifManifestBaseurlParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: Base URL for IIIF manifests.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/IIIF_MANIFEST_BASEURL
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
      Type: String
      Value: !Ref IiifManifestBaseurl
  DownloadBaseurlParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: Base URL for downloadable assets.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/DOWNLOAD_BASEURL
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
      Type: String
      Value: !Ref DownloadBaseurl
  

  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: LogPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource:
                  - !GetAtt TransformationLogGroup.Arn
        - PolicyName: EcrPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:BatchGetImage'
                Resource:
                  - !Sub arn:aws:ecr:${AWS::Region}:${ContainerAccountId}:repository/${ApplicationName}
              - Effect: Allow
                Action:
                  - 'ecr:GetAuthorizationToken'
                Resource: '*'

  TransformationUser:
    Type: AWS::IAM::User

  TransformationUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref TransformationUser

  TransformationSnsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !GetAtt TransformationUser.Arn
            Action:
              - 'sts:AssumeRole'
      Description: 'Allows user to send SNS messages.'
      Policies:
        - PolicyName: TransformationSnsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 'sns:Publish'
                Resource:
                  - !Ref EventsTopicArn

  TransformationSsmRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !GetAtt TransformationUser.Arn
            Action:
              - 'sts:AssumeRole'
      Description: 'Allows access to SSM parameters.'
      Policies:
        - PolicyName: TransformationSsmPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ssm:GetParametersByPath'
                Resource:
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ApplicationEnvironment}/${ApplicationName}

  TransformationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/rac/${ApplicationEnvironment}/digital_ingest/ecs/${ApplicationName}"
      RetentionInDays: 90

  TransformationEcsTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: "1024"
      Memory: "3072"
      ContainerDefinitions:
        - Name: !Ref ApplicationName
          Image: !Sub "${ContainerAccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ApplicationName}:${ApplicationEnvironment}"
          Essential: true
          Environment:
            - Name: ENV
              Value: !Ref ApplicationEnvironment
            - Name: AWS_ACCESS_KEY_ID
              Value: !Ref TransformationUserAccessKey
            - Name: AWS_SECRET_ACCESS_KEY
              Value: !GetAtt TransformationUserAccessKey.SecretAccessKey
            - Name: AWS_SNS_ROLE_ARN
              Value: !GetAtt TransformationSnsRole.Arn
            - Name: AWS_SSM_ROLE_ARN
              Value: !GetAtt TransformationSsmRole.Arn
            - Name: AWS_SNS_TOPIC
              Value: !Ref EventsTopicArn
          LogConfiguration:
            LogDriver: awslogs
            Options:
              "awslogs-group": !Ref TransformationLogGroup
              "awslogs-region": !Ref AWS::Region
              "awslogs-stream-prefix": "ecs"
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      Family: !Ref ApplicationName
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      RuntimePlatform:
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX

Outputs:
  TransformationArn:
    Description: Transformation ECS Task Definition ARN
    Value: !Ref TransformationEcsTask