AWSTemplateFormatVersion: 2010-09-09
Description: >
  digital-ingest-transformation

  Transforms data from Aurora and makes Accessions,
  Archival Objects, and Digital Objects in ArchivesSpace.

Parameters:
# The AWS account that hosts the Amazon Elastic Container Registry (ECR) repository
  ContainerAccountId:
    Type: String
    Description: Account ID under which container repository is located.
    Default: "817658541382"
  ApplicationEnvironment:
    Type: String
    Description: Environment in which application should be deployed.
    AllowedValues:
      - dev
      - prod
    default: dev
  ApplicationName:
    Type: String
    Description: Name of the application to be deployed.
  ArchivematicaSSAPIKey:
    Type: String
    Description: API Key for Archivematica Storage Service
  ArchivematicaSSUserName:
    Type: String
    Description: Archivematica Storage Service Username
  ArchivematicaSSUrl: 
    Type: String
    Description: URL for the Archivematica Storage Service
  ZodiacBaseurl:
    Type: String
    Description: BaseURL for the Zodiac Backend
  ASBaseurl:
    Type: String
    Description: BaseURL for the ArchivesSpace Backend
  ASUsername:
    Type: String
    Description: ArchivesSpace Username
  ASPassword:
    Type: String
    Description: ArchivesSpace Password
  ASRepoID:
    Type: Number
    Description: ArchivesSpace Repository ID
  AuroraBaseurl:
    Type: String
    Description: Aurora BaseURL
  AuroraOauthClientBaseurl:
    Type: String
    Description: Aurora OAuth Client BaseURL
  AuroraOauthClientID:
    Type: String
    Description: Aurora OAuth Client ID
  AuroraOauthClientSecret:
    Type: String
    Description: Aurora OAuth Client Secret
  AuroraAccessionStartedStatus:
    Type: String
    Description: Status of Aurora Accession at start
  AuroraPackageCompleteStatus:
    Type: String
    Description: Status of Aurora Accession at completion
  IIIFManifestBaseurl:
    Type: String
    Description: BaseURL for the IIIF manifest
  DownloadBaseurl:
    Type: String
    Description: BaseURL to download the object
  # Elastic File System (EFS) parameters for temporary storage of files as they are transformed and moved through the pipeline
  EfsId:
    Type: String
    Description: Identifier for temporary storage EFS.
  EfsAccessPointId:
    Type: String
    Description: Identifier for temporary storage EFS access point.
  EfsRootPath:
    Type: String
    Description: Root path at which EFS is mounted.
  PackageID:
    Type: String
    Description: String representation of the package identifier
  EventsTopicArn:
    Type: String
    Description: ARN for events SNS Topic

Resources:
  # I think we need this, but could be wrong.
  SnsTopicParam:
    Type: AWS::SSM::Parameter
    Properties: 
      AllowedPattern: "^[A-Za-z0-9\\-\\_]+$"
      Description: ARN for SNS topic to send messages to.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/SNS_TOPIC
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
      Type: String
      Value: !Ref EventsTopicArn

  # An ECS task definition that defines the container
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: LogPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource:
                  - !GetAtt TransformationLogGroup.Arn
        - PolicyName: EcrPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:BatchGetImage'
                Resource:
                  - !Sub arn:aws:ecr:${AWS::Region}:${ContainerAccountId}:repository/${ApplicationName}
              - Effect: Allow
                Action:
                  - 'ecr:GetAuthorizationToken'
                Resource: '*'

  TransformationUser:
    Type: AWS::IAM::User
    UserName: TransformationUser

  TransformationUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref TransformationUser

  TransformationSnsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !GetAtt TransformationUser.Arn
            Action:
              - 'sts:AssumeRole'
      Description: 'Allows user to send SNS messages.'
      Policies:
        - PolicyName: TransformationSNSPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 'sns:Publish'
                Resource:
                  - !Ref EventsTopicArn

  TransformationSsmRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !GetAtt TransformationUser.Arn
            Action:
              - 'sts:AssumeRole'
      Description: 'Allows access to SSM parameters.'
      Policies:
        - PolicyName: TransformationSSMPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ssm:GetParametersByPath'
                Resource:
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ApplicationEnvironment}/${ApplicationName}

  TransformationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/rac/${ApplicationEnvironment}/digital_ingest/ecs/${ApplicationName}"
      RetentionInDays: 90

  TransformationEcsTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: "1024"
      Memory: "3072"
      ContainerDefinitions:
        - Name: !Ref ApplicationName
          Image: !Sub "${ContainerAccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ApplicationName}:latest"
          Essential: true
          Environment:
            Variables:
              ENV: !Ref ApplicationEnvironment
              SNS_ROLE_ARN: !GetAtt TransformationSnsRole.Arn
              SSM_ROLE_ARN: !GetAtt TransformationSsmRole.Arn
              SNS_TOPIC: !Ref EventsTopicArn
              PACKAGE_ID: !Ref PackageID
              ARCHIVEMATICA_SS_API_KEY: !Ref ArchivematicaSSAPIKey
              ARCHIVEMATICA_SS_USER_NAME: !Ref ArchivematicaSSUserName
              ARCHIVEMATICA_SS_URL: !Ref ArchivematicaSSUrl
              ZODIAC_BASEURL: !Ref ZodiacBaseurl
              AS_BASEURL: !Ref ASBaseurl
              AS_USERNAME: !Ref ASUsername
              AS_PASSWORD: !Ref ASPassword
              AS_REPO_ID: !Ref ASRepoID
              AURORA_BASEURL: !Ref AuroraBaseurl
              AURORA_OAUTH_CLIENT_BASEURL: !Ref AuroraOauthClientBaseurl
              AURORA_OAUTH_CLIENT_ID: !Ref AuroraOauthClientID
              AURORA_OAUTH_CLIENT_SECRET: !Ref AuroraOauthClientSecret
              AURORA_ACCESSION_STARTED_STATUS: !Ref AuroraAccessionStartedStatus
              AURORA_PACKAGE_COMPLETE_STATUS: !Ref AuroraPackageCompleteStatus
              IIIF_MANIFEST_BASEURL: !Ref IIIFManifestBaseurl
              DOWNLOAD_BASEURL: !Ref DownloadBaseurl
              APP_CONFIG_PATH: !Ref ApplicationName
              AWS_REGION: !Ref AWS::Region
          Tags:
            - Key: Environment
              Value: !Ref ApplicationEnvironment
            - Key: Application
              Value: !Ref ApplicationName

          MountPoints:
            - SourceVolume: efs
              ContainerPath: !Ref EfsRootPath
              ReadOnly: false
          LogConfiguration:
            LogDriver: awslogs
            Options:
              "awslogs-group": !Ref TransformationLogGroup
              "awslogs-region": !Ref AWS::Region
              "awslogs-stream-prefix": "ecs"
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      Family: !Ref ApplicationName
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      RuntimePlatform:
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX
      Volumes:
        - Name: efs
          EFSVolumeConfiguration:
            FilesystemId: !Ref EfsId
            RootDirectory: /
            TransitEncryption: ENABLED
            AuthorizationConfig:
              AccessPointId: !Ref EfsAccessPointId
              IAM: DISABLED

Outputs:
  TransformationArn:
    Description: Transformation ECS Task Definition ARN
    Value: !Ref TransformationEcsTask