AWSTemplateFormatVersion: '2010-09-09'
Description: >
  digital-ingest-pipeline

  Pipeline for ingesting packages of born-digital and digitized content.

Mappings:
  DeployResources:
    CloudFormationBucket:
      dev: rac-dev-cloudformation-apps
      prod: rac-prod-cloudformation-apps
    CloudFormationBucketPrefix:
      dev: digital_ingest_pipeline
      prod: digital_ingest_pipeline
    SecurityGroup:
      dev: "sg-0f98d77d7bb7b4ce6"
      prod: "sg-0a568e8a6ff39b710"
    Subnet:
      dev: "subnet-098df07b0ab91cb1d"
      prod: "subnet-02e68cd17b1abfc14"
  TriggerLambda:
    ECSSubnetName:
      dev: "subnet-098df07b0ab91cb1d"
      prod: "subnet-0102189437e2babd8"
  DiscoveryService:
    SourceBucketName:
      dev: "rac-dev-digital-ingest-upload"
      prod: "rac-prod-digital-ingest-upload"
    DigitizationEfsId:
      dev: "fs-4ecb5eae"
      prod: "fs-b9197b5a"
    DigitizationEfsAccessPointId:
      dev: "fsap-0d530b00165a90a27"
      prod: "" # TODO
    DigitizationRootPath:
      dev: "pictor"
      prod: "pictor"
    DigitizationPath:
      dev: "src"
      prod: "src"
    DigitizationUrl:
      dev: "http://10.0.1.90:8012"
      prod: "https://10.0.1.144:8012"
  Zodiac:
    Baseurl:
      dev: "https://zodiac.dev.rockarch.org/api"  # TODO
      prod: "https://zodiac.rockarch.org/api"  # TODO
  Archivematica:
    ZodiacPlUsername:
      dev: digital_ingest_assembly
      prod: digital_ingest_assembly
    ZodiacPlUrl:
      dev: http://archivematica-zodiac.dev.rockarch.org
      prod: http://archivematica-zodiac.rockarch.org
    ZodiacPlTransferSource:
      dev: 5b6e5370-fd6a-4fb3-96db-adc17315922a
      prod: 947060a0-8d13-4f32-8c0e-0fabbf2d63e7
    ZodiacPlProcessingConfig:
      dev: automated
      prod: automated
    MainPlUsername:
      dev: digital_ingest_assembly
      prod: digital_ingest_assembly
    MainPlUrl:
      dev: http://archivematica.dev.rockarch.org
      prod: http://archivematica.rockarch.org
    MainPlTransferSource:
      dev: 5b6e5370-fd6a-4fb3-96db-adc17315922a
      prod: 947060a0-8d13-4f32-8c0e-0fabbf2d63e7
    MainPlProcessingConfig:
      dev: automated
      prod: automated
  ArchivematicaStorageService:
    Baseurl:
      dev: http://archivematica-storage-service.dev.rockarch.org:8000
      prod: http://archivematica-storage-service.rockarch.org:8000
    Username: 
      dev: digital_ingest_transformation
      prod: digital_ingest_transformation
  ArchivesSpace:
    Baseurl:
      dev: https://as.dev.rockarch.org/api
      prod: https://as.rockarch.org/api
    Username:
      dev: digital_ingest_transformation
      prod: digital_ingest_transformation
    RepoId:
      dev: 2
      prod: 2
  Aurora:
    Baseurl:
      dev: https://aurora.dev.rockarch.org/api
      prod: https://aurora.rockarch.org/api
    OauthClientBaseurl:
      dev: https://rac-aurora-dev.auth.us-east-1.amazoncognito.com
      prod: https://rac-aurora-prod.auth.us-east-1.amazoncognito.com
    AccessionStartedStatus:
      dev: 30
      prod: 30
    PackageCompleteStatus:
      dev: 90
      prod: 90
  Dimes:
    IiifManifestBaseurl:
      dev: https://iiif.dev.rockarch.org/manifests
      prod: https://iiif.rockarch.org/manifests
    DownloadBaseurl:
      dev: https://iiif.dev.rockarch.org/pdf
      prod: https://iiif.rockarch.org/pdf

Parameters:
  Environment:
    Type: String
    Description: The environment in which the infrastructure should be deployed.
    AllowedValues:
      - dev
      - prod
    Default: dev
  ArchivematicaZodiacPlApiKey:
    Type: String
    Description: Archivematica API Key for Aurora origin.
  ArchivematicaMainPlApiKey:
    Type: String
    Description: Archivematica API Key for digitization origin.
  ArchivematicaCallbackApiKey:
    Type: String
    Description: Archivematica API Key sent in post-store requests.
  ArchivematicaStorageServiceApiKey:
    Type: String
    Description: Archivematica Storage Service API Key.
  ArchivesSpaceTransformationPassword:
    Type: String
    Description: ArchivesSpace password for user associated with transformation service.
  AuroraOauthClientId:
    Type: String
    Description: Aurora OAuth Client ID.
  AuroraOauthClientSecret:
    Type: String
    Description: Aurora OAuth Client Sectret.

Resources:
  # Temporary Storage
  TemporaryStorage:
    Type: AWS::EFS::FileSystem
    Properties: 
      Encrypted: true
      FileSystemTags: 
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: digital-ingest-temporary-storage
      LifecyclePolicies:
        - TransitionToIA: AFTER_30_DAYS
      PerformanceMode: generalPurpose
      ThroughputMode: elastic

  # Temporary Storage Access Point
  TemporaryStorageAccessPoint:
    Type: 'AWS::EFS::AccessPoint'
    Properties:
      AccessPointTags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: digital-ingest-temporary-storage
      FileSystemId: !Ref TemporaryStorage
      PosixUser:
        Uid: "1000"
        Gid: "1000"
      RootDirectory:
        CreationInfo:
          OwnerGid: "1000"
          OwnerUid: "1000"
          Permissions: "755"
        Path: "/digital-ingest"

  # ECS Cluster
  DigitalIngestECSCluster:
    Type: AWS::ECS::Cluster
    Properties: 
      CapacityProviders: 
        - FARGATE
      ClusterName: DigitalIngestCluster
      Tags: 
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: digital-ingest-ecs-cluster

  # Discovery ECS Task
  DiscoveryTask:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        !Join ["/",
          [
          "https://s3.amazonaws.com",
          !FindInMap [DeployResources, CloudFormationBucket, !Ref Environment],
          !FindInMap [DeployResources, CloudFormationBucketPrefix, !Ref Environment],
          "digital_ingest_discovery_template.yaml"
          ]
        ]
      Parameters:
        ApplicationEnvironment: !Ref Environment
        ApplicationName: digital_ingest_discovery
        EfsId: !Ref TemporaryStorage
        EfsAccessPointId: !Ref TemporaryStorageAccessPoint
        EfsRootPath: '/efs'
        EventsTopicArn: !Ref DigitalIngestTopic
        StoragePath: 'storage'
        TemporaryPath: 'digital_ingest_discovery_tmp'
        SourceBucketName: !FindInMap [DiscoveryService, SourceBucketName, !Ref Environment]
        DigitizationEfsId: !FindInMap [DiscoveryService, DigitizationEfsId, !Ref Environment]
        DigitizationEfsAccessPointId: !FindInMap [DiscoveryService, DigitizationEfsAccessPointId, !Ref Environment]
        DigitizationRootPath: !FindInMap [DiscoveryService, DigitizationRootPath, !Ref Environment]
        DigitizationPath: !FindInMap [DiscoveryService, DigitizationPath, !Ref Environment]
        DigitizationUrl: !FindInMap [DiscoveryService, DigitizationUrl, !Ref Environment]

  # Assembly ECS Task
  AssemblyTask:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        !Join ["/", 
          [
          "https://s3.amazonaws.com",
          !FindInMap [DeployResources, CloudFormationBucket, !Ref Environment],
          !FindInMap [DeployResources, CloudFormationBucketPrefix, !Ref Environment],
          "digital_ingest_assembly_template.yaml"
          ]
        ]
      Parameters:
        ApplicationEnvironment: !Ref Environment
        ApplicationName: digital_ingest_assembly
        EfsId: !Ref TemporaryStorage
        EfsAccessPointId: !Ref TemporaryStorageAccessPoint
        EfsRootPath: '/efs'
        SourcePath: discovery
        TemporaryPath: assembly_tmp
        DestinationPath: assembly
        EventsTopicArn: !Ref DigitalIngestTopic
        ZodiacBaseurl: !FindInMap [Zodiac, Baseurl, !Ref Environment]
        AuroraArchivematicaApiKey: !Ref ArchivematicaZodiacPlApiKey
        AuroraArchivematicaUserName: !FindInMap [Archivematica, ZodiacPlUsername, !Ref Environment]
        AuroraArchivematicaUrl: !FindInMap [Archivematica, ZodiacPlUrl, !Ref Environment]
        AuroraArchivematicaTransferSource: !FindInMap [Archivematica, ZodiacPlTransferSource, !Ref Environment]
        AuroraArchivematicaProcessingConfig: !FindInMap [Archivematica, ZodiacPlProcessingConfig, !Ref Environment]
        DigitizationArchivematicaApiKey: !Ref ArchivematicaMainPlApiKey
        DigitizationArchivematicaUserName: !FindInMap [Archivematica,MainPlUsername, !Ref Environment]
        DigitizationArchivematicaUrl: !FindInMap [Archivematica, MainPlUrl, !Ref Environment]
        DigitizationArchivematicaTransferSource: !FindInMap [Archivematica, MainPlTransferSource, !Ref Environment]
        DigitizationArchivematicaProcessingConfig: !FindInMap [Archivematica, MainPlProcessingConfig, !Ref Environment]
        AvDigitizationArchivematicaApiKey: !Ref ArchivematicaMainPlApiKey
        AvDigitizationArchivematicaUserName: !FindInMap [Archivematica, MainPlUsername, !Ref Environment]
        AvDigitizationArchivematicaUrl: !FindInMap [Archivematica, MainPlUrl, !Ref Environment]
        AvDigitizationArchivematicaTransferSource: !FindInMap [Archivematica, MainPlTransferSource, !Ref Environment]
        AvDigitizationArchivematicaProcessingConfig: !FindInMap [Archivematica, MainPlProcessingConfig, !Ref Environment]
        LegacyDigitalArchivematicaApiKey: !Ref ArchivematicaZodiacPlApiKey
        LegacyDigitalArchivematicaUserName: !FindInMap [Archivematica, ZodiacPlUsername, !Ref Environment]
        LegacyDigitalArchivematicaUrl: !FindInMap [Archivematica, ZodiacPlUrl, !Ref Environment]
        LegacyDigitalArchivematicaTransferSource: !FindInMap [Archivematica, ZodiacPlTransferSource, !Ref Environment]
        LegacyDigitalArchivematicaProcessingConfig: !FindInMap [Archivematica, ZodiacPlProcessingConfig, !Ref Environment]

  # Transformation ECS Task
  TransformationTask:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        !Join ["/",
          [
          "https://s3.amazonaws.com",
          !FindInMap [DeployResources, CloudFormationBucket, !Ref Environment],
          !FindInMap [DeployResources, CloudFormationBucketPrefix, !Ref Environment],
          "digital_ingest_transformation_template.yaml"
          ]
        ]
      Parameters:
        ApplicationEnvironment: !Ref Environment
        ApplicationName: digital_ingest_transformation
        EfsId: !Ref TemporaryStorage
        EfsAccessPointId: !Ref TemporaryStorageAccessPoint
        EfsRootPath: '/efs'
        EventsTopicArn: !Ref DigitalIngestTopic
        ArchivematicaSsApiKey: !Ref ArchivematicaStorageServiceApiKey
        ArchivematicaSsUserName: !FindInMap [ArchivematicaStorageService, Username, !Ref Environment]
        ArchivematicaSsUrl: !FindInMap [ArchivematicaStorageService, Baseurl, !Ref Environment]
        ZodiacBaseurl: !FindInMap [Zodiac, Baseurl, !Ref Environment]
        ArchivesSpaceBaseurl: !FindInMap [ArchivesSpace, Baseurl, !Ref Environment]
        ArchivesSpaceUsername: !FindInMap [ArchivesSpace, Username, !Ref Environment]
        ArchivesSpacePassword: !Ref ArchivesSpaceTransformationPassword
        ArchivesSpaceRepoId: !FindInMap [ArchivesSpace, RepoId, !Ref Environment]
        AuroraBaseurl: !FindInMap [Aurora, Baseurl, !Ref Environment]
        AuroraOauthClientBaseurl: !FindInMap [Aurora, OauthClientBaseurl, !Ref Environment]
        AuroraOauthClientId: !Ref AuroraOauthClientId
        AuroraOauthClientSecret: !Ref AuroraOauthClientSecret
        AuroraAccessionStartedStatus: !FindInMap [Aurora, AccessionStartedStatus, !Ref Environment]
        AuroraPackageCompleteStatus: !FindInMap [Aurora, PackageCompleteStatus, !Ref Environment]
        IiifManifestBaseurl: !FindInMap [Dimes, IiifManifestBaseurl, !Ref Environment]
        DownloadBaseurl: !FindInMap [Dimes, DownloadBaseurl, !Ref Environment]

  # SNS topic
  DigitalIngestTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: digital-ingest-notifications

  # SQS Notifications Queue
  DigitalIngestNotificationsQueue:
    Type: AWS::SQS::Queue
    Properties:
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: digital-ingest-notifications-queue

  # SQS Trigger Queue
  DigitalIngestTriggerQueue:
    Type: AWS::SQS::Queue
    Properties:
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: digital-ingest-notifications-queue

  # SNS Subscription for SQS Notifications Queue
  DigitalIngestNotificationsQueueSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref DigitalIngestTopic
      Protocol: sqs
      Endpoint: !GetAtt DigitalIngestNotificationsQueue.Arn
      FilterPolicy: '"requested_status": [{"exists": false}]'
      FilterPolicyScope: MessageAttributes

  # SNS Subscription for SQS Trigger Queue
  DigitalIngestTriggerQueueSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref DigitalIngestTopic
      Protocol: sqs
      Endpoint: !GetAtt DigitalIngestTriggerQueue.Arn
      FilterPolicy: '"requested_status": [{"exists": true}]'
      FilterPolicyScope: MessageAttributes

  # Notifications Lambda
  NotificationsLambda:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        !Join ["/",
          [
          "https://s3.amazonaws.com",
          !FindInMap [DeployResources, CloudFormationBucket, !Ref Environment],
          !FindInMap [DeployResources, CloudFormationBucketPrefix, !Ref Environment],
          "digital_ingest_notifications_template.yaml"
          ]
        ]
      Parameters:
        ApplicationEnvironment: !Ref Environment
        ApplicationName: digital_ingest_notifications
        EventsTopicArn: !Ref DigitalIngestTopic
        NotificationsQueueArn: !Ref DigitalIngestNotificationsQueue
        ZodiacBaseurl: !FindInMap [Zodiac, Baseurl, !Ref Environment]

  # Trigger Lambda
  TriggerLambda:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        !Join ["/",
          [
          "https://s3.amazonaws.com",
          !FindInMap [DeployResources, CloudFormationBucket, !Ref Environment],
          !FindInMap [DeployResources, CloudFormationBucketPrefix, !Ref Environment],
          "digital_ingest_trigger_template.yaml"
          ]
        ]
      Parameters:
        ApplicationEnvironment: !Ref Environment
        ApplicationName: digital_ingest_trigger
        ECSClusterName: !Ref DigitalIngestECSCluster
        ECSSubnetName: !FindInMap [TriggerLambda, ECSSubnetName, !Ref Environment]
        ParentStackName: !Ref AWS::StackName
        SourceBucketName: !FindInMap [DiscoveryService, SourceBucketName, !Ref Environment]
        TriggerQueueArn: !Ref DigitalIngestTriggerQueue

  # Webhook Lambda
  WebhookLambda:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        !Join ["/",
          [
          "https://s3.amazonaws.com",
          !FindInMap [DeployResources, CloudFormationBucket, !Ref Environment],
          !FindInMap [DeployResources, CloudFormationBucketPrefix, !Ref Environment],
          "digital_ingest_webhook_template.yaml"
          ]
        ]
      Parameters:
        ApplicationEnvironment: !Ref Environment
        ApplicationName: digital_ingest_webhook
        ArchivematicaApiKey: !Ref ArchivematicaCallbackApiKey
        NotificationsTopicArn: !Ref DigitalIngestTopic