AWSTemplateFormatVersion: '2010-09-09'
Description: >
  digital-ingest-trigger

  Triggers next event in digital ingest pipeline.

Parameters:
  ApplicationEnvironment:
    Type: String
    Description: Environment in which the application should be deployed.
    AllowedValues:
      - dev
      - prod
  ApplicationName:
    Type: String
    Description: Name of the application to be deployed.
  ECSClusterName:
    Type: String
    Description: Name of the ECS Cluster in which the Task should be triggered.
  ECSSubnetName:
    Type: AWS::EC2::Subnet::Id
    Description: Name of the subnet in which the ECS Task should be triggered.
  ECSSecurityGroupName:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Name of the security group for the Task.
  ExpansionRatio:
    Type: String
    Description: Expansion ratio for compressed files
    Default: 4.0
  ParentStackName:
    Type: String
    Description: Name of the parent stack
  TriggerQueueArn:
    Type: String 
    Description: ARN of trigger SQS Queue
  Workload:
    Type: String
    Description: Name of workload for this stack.

Resources:
  # Source bucket
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: Environment
          Value: !Ref ApplicationEnvironment
        - Key: Application
          Value: !Ref ApplicationName
        - Key: Workload
          Value: !Ref Workload
      BucketName: !Sub rac-${ApplicationEnvironment}-digital-ingest-upload
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      NotificationConfiguration:
        LambdaConfigurations:
          - Function: !GetAtt DigitalIngestTriggerFunction.Arn
            Event: 's3:ObjectCreated:*'

  DigitalIngestTriggerFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      Tags:
        - Key: Environment
          Value: !Ref ApplicationEnvironment
        - Key: Application
          Value: !Ref ApplicationName
        - Key: Workload
          Value: !Ref Workload
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: IAM Role which supports running ECS Tasks and Services.
      Policies: 
        - PolicyName: DigitalIngestTriggerRunECSTaskPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'ecs:RunTask'
                Resource:
                  - !Sub 'arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:task-definition/digital_ingest_*'
                  - !Sub 'arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:task-definition/iiif_*'
              - Effect: Allow
                Action: 'ecs:DescribeServices'
                Resource: !Sub 'arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:service/${ECSClusterName}/*'
              - Effect: Allow
                Action: 'ecs:UpdateService'
                Resource: !Sub 'arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:service/${ECSClusterName}/*'
              - Effect: Allow
                Action: 'iam:PassRole'
                Resource: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/${ParentStackName}-*'
                Condition:
                  StringLike:
                    'iam:PassedToService': 'ecs-tasks.amazonaws.com'
              - Effect: Allow
                Action: 
                  - 'ecs:ListTasks'
                Resource: !Sub 'arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:container-instance/${ECSClusterName}/*'
              - Effect: Allow
                Action: 'ecs:ExecuteCommand'
                Resource: 
                  - !Sub arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:cluster/${ECSClusterName}
                  - !Sub arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:task/${ECSClusterName}/*
        - PolicyName: DigitalIngestTriggerParameterStorePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 'ssm:GetParametersByPath*'
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ApplicationEnvironment}/${ApplicationName}*'
        - PolicyName: DigitalIngestTriggerLogPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: !GetAtt TriggerLogGroup.Arn
        - PolicyName: DigitalIngestTriggerSQSPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 'sqs:ReceiveMessage'
                  - 'sqs:DeleteMessage'
                  - 'sqs:GetQueueAttributes'
                Resource: !Ref TriggerQueueArn
        - PolicyName: PassEcsInfrastructureRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 'iam:PassRole'
                Resource: !GetAtt EcsInfrastructureRole.Arn
                Condition:
                  StringEquals:
                    iam:PassedToService: ecs.amazonaws.com

  ECSClusterParam:
    Type: AWS::SSM::Parameter
    Properties: 
      AllowedPattern: "^[A-Za-z0-9\\-\\_]+$"
      Description: Name of ECS Cluster in which Task should be triggered.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/ECS_CLUSTER
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
        Workload: !Ref Workload
        WorkloadType: processing
      Type: String
      Value: !Ref ECSClusterName
  ECSSubnetParam:
    Type: AWS::SSM::Parameter
    Properties: 
      AllowedPattern: "^[A-Za-z0-9\\-\\_]+$"
      Description: Subnet in which ECS Task should be triggered.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/ECS_SUBNET
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
        Workload: !Ref Workload
        WorkloadType: processing
      Type: String
      Value: !Ref ECSSubnetName
  ECSSecurityGroupParam:
    Type: AWS::SSM::Parameter
    Properties: 
      AllowedPattern: "^[A-Za-z0-9\\-\\_]+$"
      Description: Subnet in which ECS Task should be triggered.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/ECS_SECURITY_GROUP
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
        Workload: !Ref Workload
        WorkloadType: processing
      Type: String
      Value: !Ref ECSSecurityGroupName
  ExpansionRatioParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Ratio at which uncompressed packages expand
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/EXPANSION_RATIO
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
        Workload: !Ref Workload
        WorkloadType: processing
      Type: String
      Value: !Ref ExpansionRatio
  EbsVolumeRole:
    Type: AWS::SSM::Parameter
    Properties:
      Description: IAM role which allows ECS to configure volumes
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/EBS_VOLUME_ROLE
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
        Workload: !Ref Workload
        WorkloadType: processing
      Type: String
      Value: !GetAtt EcsInfrastructureRole.Arn
  
  EcsInfrastructureRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSInfrastructureRolePolicyForVolumes

  DigitalIngestTriggerFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub 'rac-${ApplicationEnvironment}-lambda'
        S3Key: !Sub '${ApplicationName}.zip'
      FunctionName: !Ref ApplicationName
      Handler: handle_digital_ingest_trigger.lambda_handler
      LoggingConfig:
        LogGroup: !Ref TriggerLogGroup
      Role: !GetAtt DigitalIngestTriggerFunctionRole.Arn
      Runtime: python3.11
      Timeout: 10
      Environment:
        Variables:
          ENV: !Ref ApplicationEnvironment
          APP_CONFIG_PATH: !Ref ApplicationName
      Architectures:
        - x86_64
      Tags:
        - Key: Environment
          Value: !Ref ApplicationEnvironment
        - Key: Application
          Value: !Ref ApplicationName
        - Key: Workload
          Value: !Ref Workload
        - Key: WorkloadType
          Value: processing

  S3InvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt DigitalIngestTriggerFunction.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub arn:aws:s3:::rac-${ApplicationEnvironment}-digital-ingest-upload
      SourceAccount: !Ref AWS::AccountId

  TriggerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      Tags:
        - Key: Environment
          Value: !Ref ApplicationEnvironment
        - Key: Application
          Value: !Ref ApplicationName
        - Key: Workload
          Value: !Ref Workload
        - Key: WorkloadType
          Value: processing
      LogGroupName: !Sub "/aws/lambda/${ApplicationName}"
      RetentionInDays: 90

  # Subscribe Lambda to SQS
  DigitalIngestNotificationsEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !Ref TriggerQueueArn
      FunctionName: !GetAtt DigitalIngestTriggerFunction.Arn

Outputs:
  DigitalIngestTriggerFunction:
    Description: "Digital Ingest Trigger Lambda Function ARN"
    Value: !GetAtt DigitalIngestTriggerFunction.Arn
